apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  labels:
    name: db-env
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "helmproject-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
  ## DB_PASSWORD: DWumjpgjw3
