apiVersion: v1
kind: Service
metadata:
  name: helmproject
spec:
  selector:
    app.kubernetes.io/name: helmproject
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmproject
  labels:
    name: helmproject

spec:
  replicas: 1
  selector:
    matchLabels:
      service: helmproject
  template:
    metadata:
      labels:
        service: helmproject
    spec:
      containers:
      - name: helmproject
        image: 196116466484.dkr.ecr.us-east-1.amazonaws.com/udacityproject:0.8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5

        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always