apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: default
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
